### ISSUE TITLE
Popping Rotation

### ISSUE THREAD

**Issue by joshuacrowley** [pjarmalavicius/react-rotatable#1]
Thank you for this package!

I'm finding that often when I start a drag, the handle will pop about 30º or so unexpectedly. Also the handle is a little jerky on rotation. Do you have any advice on how I might correct this behaviour, or how I might be creating the issue?

You can see a demo of my implementation [here](http://assessments-storybook.s3-website-ap-southeast-2.amazonaws.com/?selectedKind=Rotation&selectedStory=SOT1&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel).

**Comment by pjarmalavicius** [comment]
Thank you for your notes. It is indeed a bug because scroll top value is ignored on rotation start. I hope I will fix it soon

**Comment by joshuacrowley** [comment]
@pjarmalavicius thank you very much!
